### ISSUE TITLE
Issue with Carwash Coords

### ISSUE THREAD

**Issue by ADRNALN** [Qbox-project/qbx_smallresources#32]
### Summary

After the recent carwash update/changes this error appears client side

### Reproduction

[ae934aa](https://github.com/Qbox-project/qbx-smallresources/commit/ae934aa5269ed078fb0b0b8afb009ba7d6023ffe)

![image](https://github.com/Qbox-project/qbx-smallresources/assets/32118783/164e4e19-d788-4170-88bd-7d19978980bd)

![image](https://github.com/Qbox-project/qbx-smallresources/assets/32118783/2f1fda2a-1513-4f82-9b1e-92fbd22a7cda)

### Expected behavior

Car wash blips should appear on the map

### Actual behavior

Car wash blips do not appear and error is present client side

### Additional context

Carwashes do not appear on the map either, I think the main reason is the label field it calls doesn't even exist in the config anymore.

### Last Updated

Few days ago

### Custom Resources

Nope

### Resource Rename

Nope

**Comment by jnccloud** [comment]
Confirmed. PR submitted to fix this.
