### ISSUE TITLE
Break up smallresources

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qbx_smallresources#43]
### The problem

- the config is confusing to navigate
- servers may want some of the features but not all
- lose out on features of resources like the ability to reload/disable
- harms readability as all the files share the same resource visibility, so it's not guaranteed as a reader that there isn't a hidden global variable or function shared by two resources

### Ideal solution

identify logical splits for where new resources should be created. Some examples:

qbx_afk - checks for afk players and kicks them
qbx_carwash - gives the carwashes around the map the ability to clean cars
qbx_binocular - creates a usable binocular item with zoom functionality

**Comment by alberttheprince** [comment]
I agree - small resource should be very simple resources that can be reset with no impact on players/users. It should all fit within one or two files, basically a collect of snippets.

Why not just make a directory rather than a single resource that contains all these resources individually with their own fxmanifest?

**Comment by Manason** [comment]
> I agree - small resource should be very simple resources that can be reset with no impact on players/users. It should all fit within one or two files, basically a collect of snippets.
> 
> Why not just make a directory rather than a single resource that contains all these resources individually with their own fxmanifest?

We could, and it would be an improvement for sure, but why do these snippets deserve to go together in the first place? If we were designing this structure from scratch, we wouldn't have any reason to group these resources together under a directory. They have nothing to do with each other aside from their size, but I don't think size is a useful organization paradigm.

**Comment by alberttheprince** [comment]
As far as I've seen from server management, group resources like this only purpose is for server owners to brag about how "little" resources they have on their server or to hide resources from the public. I'm not sure if there's any performance or organizational benefit, but I think you could just totally split all of them into individual resources and be done with it.

**Comment by artur-michalak** [comment]
I have separated everything into subdirectories, I think this will help in further work.
